FROM rhel

MAINTAINER Kim Daniel Engebretsen

# Enironment variables
# TODO: Set this to autofetch 
ENV PROXY_FQDN=127.0.0.1

# Install packages
ADD redhat.repo /etc/yum.repos.d/redhat.repo
RUN yum -y install haproxy etcd

# Copy config files 
RUN mkdir /cfg
ADD haproxy.cfg /cfg/haproxy.cfg
ADD run.sh /cfg/run.sh
ADD netsed /cfg/netsed
ADD combined.pem /etc/ssl/private/combined.pem

# Setting netsed to rewrite hostname references in all tcp packets
RUN echo "/cfg/netsed tcp 8080 127.0.0.1 80 's/$PROXY_FQDN/openam.localdomain.local' > /dev/null 2>&1 &" >> /cfg/run.sh
# Setting up haproxy for proxying netsed, infrastructure and services (OpenAM, OpenDJ and OpenIDM)
RUN echo "haproxy -f /cfg/haproxy.cfg &" >> /cfg/run.sh
# Using etcd to register and maintain each server pool per service
RUN echo "etcd" >> /cfg/run.sh

# Expose ports for global use
EXPOSE 636 389 443

# Set script to execute on run
CMD ["/cfg/run.sh"]
